defmodule SoonReady.Repo.Migrations.UpdateSurveyReadModel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:respondents__read_models__survey) do
      remove :context_questions
      remove :demographic_questions
      remove :screening_questions
      remove :job_steps
      remove :market
      remove :brand
      add :starting_page_id, :uuid, null: false
      add :pages, {:array, :map}
    end
  end

  def down do
    alter table(:respondents__read_models__survey) do
      remove :pages
      remove :starting_page_id
      add :brand, :text
      add :market, :map
      add :job_steps, {:array, :map}
      add :screening_questions, {:array, :map}
      add :demographic_questions, {:array, :map}
      add :context_questions, {:array, :map}
    end
  end
end
