defmodule SoonReady.Repo.Migrations.AddUserAndToken do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_authentication__entities__users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :username, :citext, null: false
      add :hashed_password, :text, null: false
    end

    create unique_index(:user_authentication__entities__users, [:username],
             name: "user_authentication__entities__users_unique_username_index"
           )

    create table(:user_authentication__entities__tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end
  end

  def down do
    drop table(:user_authentication__entities__tokens)

    drop_if_exists unique_index(:user_authentication__entities__users, [:username],
                     name: "user_authentication__entities__users_unique_username_index"
                   )

    drop table(:user_authentication__entities__users)
  end
end
