defmodule SoonReady.Repo.Migrations.CreateTableIdentityAndAccessManagementResourcesResearchers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:identity_and_access_management__resources__researchers, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true

      add :user_id,
          references(:user_authentication__entities__users,
            column: :id,
            name: "identity_and_access_management__resources__researchers_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(
           :identity_and_access_management__resources__researchers,
           "identity_and_access_management__resources__researchers_user_id_fkey"
         )

    drop table(:identity_and_access_management__resources__researchers)
  end
end
