defmodule SoonReady.Repo.Migrations.CreateTableQuantifyingNeedsSurveyResponseEncryptionCiphers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:quantifying_needs__survey_response__encryption__ciphers, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :cloak_key, :text, null: false
    end
  end

  def down do
    drop table(:quantifying_needs__survey_response__encryption__ciphers)
  end
end
