defmodule SoonReady.Repo.Migrations.InstallAshFunctionsExtenstion do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:identity_and_access_management__resources__users) do
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    execute(
      "ALTER INDEX identity_and_access_management__resources__users_unique_username_index RENAME TO iam__resources__users_unique_username_index"
    )

    alter table(:identity_and_access_management__resources__tokens) do
      modify :created_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:identity_and_access_management__resources__tokens) do
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
      modify :created_at, :utc_datetime_usec, default: fragment("now()")
    end

    execute(
      "ALTER INDEX iam__resources__users_unique_username_index RENAME TO identity_and_access_management__resources__users_unique_username_index"
    )

    alter table(:identity_and_access_management__resources__users) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
    end
  end
end
