defmodule SoonReady.Repo.Migrations.CreatePersonalIdentifiableInformationEncryptionKeyTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:identity_and_access_management__resources__pii_encryption_key,
             primary_key: false
           ) do
      add :user_id, :uuid, null: false, primary_key: true
      add :encoded_key, :text, null: false
    end
  end

  def down do
    drop table(:identity_and_access_management__resources__pii_encryption_key)
  end
end
